// =============================================================================
// BizOS — Expense Types
// Covers: expense categories, daily expenses, recurring expenses, query params
// =============================================================================

import type { UUID, ISODateString, Cents, HexColor, UrlString } from './common.types';
import type { PaymentMethod, PaginationParams, SoftDeletable } from './common.types';

// ─── Expense Frequency ───────────────────────────────────────────────────────

export type ExpenseFrequency = 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY';

// ─── Expense Category ─────────────────────────────────────────────────────────

export interface ExpenseCategory extends SoftDeletable {
  readonly id: UUID;
  readonly shopId: UUID;
  readonly name: string;
  /** Hex color code for UI display (e.g. "#FF5722") */
  readonly color: HexColor | null;
  /** Icon identifier (e.g. Lucide icon name) */
  readonly icon: string | null;
  /** True for system-seeded categories (cannot be deleted) */
  readonly isSystem: boolean;
}

export type ExpenseCategoryRef = Pick<ExpenseCategory, 'id' | 'name' | 'color' | 'icon'>;

// ─── Expense ──────────────────────────────────────────────────────────────────

export interface Expense extends SoftDeletable {
  readonly id: UUID;
  readonly shopId: UUID;
  readonly categoryId: UUID | null;
  readonly category: ExpenseCategoryRef | null;
  readonly title: string;
  readonly description: string | null;
  readonly amountCents: Cents;
  readonly paymentMethod: PaymentMethod;
  readonly receiptUrl: UrlString | null;
  readonly expenseDate: ISODateString;
  readonly recordedBy: UUID;
  readonly recordedByName: string | null;
  /** True if this was auto-generated by a RecurringExpense */
  readonly isRecurring: boolean;
}

// ─── Recurring Expense ────────────────────────────────────────────────────────

export interface RecurringExpense {
  readonly id: UUID;
  readonly shopId: UUID;
  readonly categoryId: UUID | null;
  readonly category: ExpenseCategoryRef | null;
  readonly title: string;
  readonly description: string | null;
  readonly amountCents: Cents;
  readonly paymentMethod: PaymentMethod;
  readonly frequency: ExpenseFrequency;
  readonly startDate: ISODateString;
  readonly endDate: ISODateString | null;
  readonly nextDueDate: ISODateString;
  readonly lastGenDate: ISODateString | null;
  readonly isActive: boolean;
  readonly recordedBy: UUID;
  readonly createdAt: ISODateString;
  readonly updatedAt: ISODateString;
}

// ─── Expense Summary ──────────────────────────────────────────────────────────

export interface ExpenseSummary {
  readonly totalAmountCents: Cents;
  readonly count: number;
  readonly byCategory: ReadonlyArray<{
    readonly categoryId: UUID;
    readonly categoryName: string;
    readonly color: HexColor | null;
    readonly amountCents: Cents;
    readonly percentage: number;
  }>;
  readonly byPaymentMethod: ReadonlyArray<{
    readonly method: PaymentMethod;
    readonly amountCents: Cents;
    readonly count: number;
  }>;
}

// ─── Request DTOs ─────────────────────────────────────────────────────────────

export interface ExpenseCategoryRequest {
  name: string;
  color?: string;
  icon?: string;
}

export interface CreateExpenseRequest {
  title: string;
  description?: string;
  categoryId?: UUID;
  amountCents: number;
  paymentMethod?: PaymentMethod;
  receiptUrl?: string;
  expenseDate?: string;
  isRecurring?: boolean;
}

export type UpdateExpenseRequest = Partial<CreateExpenseRequest>;

export interface CreateRecurringExpenseRequest {
  title: string;
  description?: string;
  categoryId?: UUID;
  amountCents: number;
  paymentMethod?: PaymentMethod;
  frequency: ExpenseFrequency;
  startDate: string;
  endDate?: string;
  isActive?: boolean;
}

export type UpdateRecurringExpenseRequest = Partial<CreateRecurringExpenseRequest>;

export interface ExpenseQueryParams extends PaginationParams {
  categoryId?: UUID;
  isRecurring?: boolean;
  startDate?: Date;
  endDate?: Date;
  search?: string;
}

export interface RecurringExpenseQueryParams extends PaginationParams {
  isActive?: boolean;
  search?: string;
}
